brew "ag"
brew "hub"
brew "gnupg"
brew "gpg2"
brew "pinentry-mac"
brew "python3"
brew "pwgen"
brew "tree"

# Install Mac applications via Homebrew Cask
cask "aerial"
cask "iterm2"
cask "java"
cask "xquartz"
