#!/usr/bin/env bash
#
# Install python packages in virtualenv ~/.venv

cd "$(dirname "$0")/.."
DOTFILES_ROOT=$(pwd)

echo "Setup virtualenv in ~/.venv"
virtualenv --no-site-packages --python=python2.7 ~/.venv

echo "Installing python packages in virtualenv ~/.venv"
cd $DOTFILES_ROOT/python && ~/.venv/bin/pip install -r requirements.txt
