#!/usr/bin/env bash
#
# Install python packages in virtualenv ~/.venv

cd "$(dirname "$0")/.."
DOTFILES_ROOT=$(pwd)

curl -O https://bootstrap.pypa.io/get-pip.py
python3 get-pip.py --user
rm get-pip.py

echo "Installing python packages in virtualenv ~/.venv"
cd $DOTFILES_ROOT/python && sudo pip3 install -r requirements.txt
