#!/usr/bin/env bash
#
# bootstrap installs things.

cd "$(dirname "$0")/.."
DOTFILES_ROOT=$(pwd)

set -e

echo ''

brew_install () {
    for brewfile in $(find -H "$DOTFILES_ROOT" -maxdepth 2 -name 'Brewfile'); do
        brew bundle --file "${brewfile}"
    done
}

echo "Installing homebrew packages..."
brew_install

echo ''
echo '  All installed!'
